trigger:
  - none

pool:
  name: 'Azure Pipelines'

steps:
  - script: mvn install
    displayName: 'Maven Install'

  - script: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install" || true
    displayName: 'Install Playwright Browsers'

  - script: mvn test
    displayName: 'Run Playwright Tests'
