
stages:
  - test

variables:
  NODE_ENV: test
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

cache:
  paths:
    - node_modules/

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.43.1-jammy
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx @playwright/mcp@latest --browser=chrome --headless --port=3000 &
    - sleep 5  # Give MCP server time to start
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
    reports:
      junit: test-results/results.xml
